Ehub 183
entando-samples/entando-hub pull request #109
Opened 2022-01-13 11:41 UTC by AkhileshPrajapatiNV

EHUB-186 ,EHUB-183,EHUB-185 developed in same branch. These changeset is from new hub setup.
 Please review and let me know if anything needs to change.

2022-01-13 11:42 UTC, AkhileshPrajapatiNV commented
@nshaw I updated application-dev.yaml as well for postgresSQL support that was pending with me.

2022-01-13 21:36 UTC, nshaw requested changes
@AkhileshPrajapatiNV , I'm afraid this won't work. The goal is to be able to control the changeset from one version to the next. If we rely on hibernate for any tables, then we cannot change the data model without breaking an existing implementation.  We need a complete changeset that represents the initial hibernate database so we can incrementally update the database going forward. Unfortunately this is the right time to implement that change, before we start fully populating the Hub and/or clients/partners install it.

2022-01-18 18:14 UTC, SACHIN-BAGHEL commented
> 

Now all the changeset are managed by liquibase

2022-01-21 00:58 UTC, nshaw approved these changes

2022-01-21 00:59 UTC, merged