EHUB-278: adds catalog details in bundle group
entando-samples/entando-hub pull request #184
Opened 2023-02-16 17:04 UTC by antromeo

2023-02-21 10:19 UTC, firegloves requested changes

2023-02-21 10:19 UTC, firegloves commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupController.java
> +import javassist.NotFoundException;
javassist is supposed to manage bytecode manipulation, please conform the code to the other controllers or, if you need an exception to ease the flow as you do for example in the validate methods of the controllers, consider using `ResponseStatusException` or creating a new custom exception extending `ResponseStatusException`

2023-02-21 10:19 UTC, firegloves commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/persistence/entity/BundleGroup.java
> +    private Boolean isPublic;
Please rename the field as `public`, the `isPublic` method is conventionally used as getter of a boolean property instead of `getIsPublic` and the `setPublic` method is conventionally used as setter of a boolean instead of `setIsPublic`

2023-02-21 10:19 UTC, firegloves commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupController.java
> +    public ResponseEntity<Object> deleteBundleGroup(@PathVariable Long bundleGroupId) {
When you are returning an empty response, the preferred and idiomatic way is to use a `ResponseEntity<Void>`. To instantiate it. Please update it where required

2023-02-21 10:19 UTC, firegloves commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/service/BundleGroupService.java
> -    	logger.debug("{}: getBundleGroup: Get a bundle group by bundle group id: {}", CLASS_NAME, bundleGroupId);
restore the logger line please

2023-02-24 08:38 UTC, alepintus commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupVersionController.java
> +        Optional<com.entando.hub.catalog.persistence.entity.BundleGroup> bundleGroupOptional = bundleGroupService.getBundleGroup(Long.parseLong(bundleGroupVersionView.getBundleGroupId()));
Please add an an import for the BundleGroup class to simplify this declaration.

2023-02-24 08:38 UTC, alepintus commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupVersionController.java
> +    public PagedContent<BundleGroupVersionFilteredResponseView, com.entando.hub.catalog.persistence.entity.BundleGroupVersion> getBundleGroupVersions(@PathVariable Long bundleGroupId, @RequestParam I
Please add an import for the BundleGroupVersion class to simplify this method definition.

2023-02-24 08:57 UTC, alepintus commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupVersionController.java
> +        Optional<com.entando.hub.catalog.persistence.entity.BundleGroup> bundleGroupOptional = bundleGroupService.getBundleGroup(Long.parseLong(bundleGroupVersionView.getBundleGroupId()));
As agreed during the meeting we decided to address these changes in a dedicated PR in the next days.

2023-02-24 08:57 UTC, alepintus commented on application/microservices/entando-hub-catalog-ms/src/main/java/com/entando/hub/catalog/rest/BundleGroupVersionController.java
> +    public PagedContent<BundleGroupVersionFilteredResponseView, com.entando.hub.catalog.persistence.entity.BundleGroupVersion> getBundleGroupVersions(@PathVariable Long bundleGroupId, @RequestParam I
As agreed during the meeting we decided to address these changes in a dedicated PR in the next days.

2023-02-24 08:58 UTC, alepintus approved these changes

2023-02-24 09:23 UTC, firegloves approved these changes
LGTM

2023-02-27 08:56 UTC, merged