Ehub 129
entando-samples/entando-hub pull request #65
Opened 2021-11-24 12:53 UTC by vijayyadav10

2021-11-29 13:04 UTC, ShreyasBhargavaNV requested changes

2021-11-29 13:50 UTC, vijayyadav10 commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/page/catalog/catalog-tile/modal-delete-bundle-group/ModalDeleteBundleGroup.js
> +                        Are you sure you want to delete this bundle?
done as suggested.

2021-11-29 13:50 UTC, vijayyadav10 commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/page/catalog/catalog-tile/modal-update-bundle-group/ModalUpdateBundleGroup.js
> +      if ((bundleGroup.status === BUNDLE_STATUS.NOT_PUBLISHED || bundleGroup.status === BUNDLE_STATUS.DELETE_REQ) &&
done as suggested(added null checks)

2021-11-29 13:50 UTC, vijayyadav10 commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/page/catalog/catalog-tile/overflow-menu/CatalogTileOverflowMenu.js
> +    const isDeletableBundle = bundleStatus === 'DELETE_REQ' ? true : false
added to constant file

2021-11-29 13:51 UTC, vijayyadav10 commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/integration/Integration.js
>    return checkForErrorsAndSendResponse(data, isError, "editedBundleGroup")
added to constant file

2021-11-30 06:29 UTC, ShreyasBhargavaNV commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/integration/Integration.js
> +  return checkForErrorsAndSendResponse(data, isError, "deletedBundle")
deletedBundle this should come from constant file

2021-11-30 06:29 UTC, ShreyasBhargavaNV commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/page/catalog/catalog-tile/modal-delete-bundle-group/ModalDeleteBundleGroup.js
> +                secondaryButtonText="Cancel"
"Cancle" should come from Constant

2021-11-30 06:35 UTC, ShreyasBhargavaNV commented on application/ui/widgets/eh-widgets-dir/eh-widgets/src/components/forms/BundleGroupForm/update-boundle-group/bundles-of-bundle-group/BundlesOfBundleGroup.js
>          bundleUrlErrorResult = validationResult["gitRepo"] &&
gitRepo should come from constant file

2021-11-30 06:41 UTC, ShreyasBhargavaNV approved these changes

2021-11-30 06:41 UTC, merged